# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1a70b4c790d8ec6399c4574ed89e9c2cf0a172b81791c6db3b10f81534dca535fe2cc771eb8e6f5cebb13102da703f93ebfb5c73e4a8e78afad2b96377a7f15

test:
  secret_key_base: 5eec52364aaf32c324de06ecb07d6857e1a85eb46fbeaa53a9a034be2aa2bc8610c2540533a03cd31deba9ff4c47646df4fe16f8e3248a778de3c05eafc483bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
